CREATE TABLE IF NOT EXISTS public.analysis_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_path text NOT NULL,
  status text NOT NULL DEFAULT 'uploaded',
  report_text text NULL,
  error_text text NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT analysis_jobs_status_check CHECK (status IN ('uploaded', 'processing', 'report_ready', 'failed'))
);

CREATE TABLE IF NOT EXISTS public.processed_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id uuid NOT NULL REFERENCES public.analysis_jobs(id) ON DELETE CASCADE,
  row_index integer NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS analysis_jobs_user_created_idx
ON public.analysis_jobs (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS processed_data_job_row_idx
ON public.processed_data (job_id, row_index);

CREATE OR REPLACE FUNCTION public.set_analysis_jobs_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS analysis_jobs_set_updated_at ON public.analysis_jobs;
CREATE TRIGGER analysis_jobs_set_updated_at
BEFORE UPDATE ON public.analysis_jobs
FOR EACH ROW
EXECUTE FUNCTION public.set_analysis_jobs_updated_at();

ALTER TABLE public.analysis_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.processed_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own analysis jobs" ON public.analysis_jobs;
CREATE POLICY "Users can read own analysis jobs"
ON public.analysis_jobs
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can insert own analysis jobs" ON public.analysis_jobs;
CREATE POLICY "Users can insert own analysis jobs"
ON public.analysis_jobs
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can update own analysis jobs" ON public.analysis_jobs;
CREATE POLICY "Users can update own analysis jobs"
ON public.analysis_jobs
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can read own processed data" ON public.processed_data;
CREATE POLICY "Users can read own processed data"
ON public.processed_data
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.analysis_jobs j
    WHERE j.id = processed_data.job_id
      AND j.user_id = auth.uid()
  )
);

INSERT INTO storage.buckets (id, name, public)
VALUES ('uploaded-excels', 'uploaded-excels', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Users can upload own excel files" ON storage.objects;
CREATE POLICY "Users can upload own excel files"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'uploaded-excels' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Users can read own excel files" ON storage.objects;
CREATE POLICY "Users can read own excel files"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'uploaded-excels' AND auth.uid() = owner);

DROP POLICY IF EXISTS "Users can delete own excel files" ON storage.objects;
CREATE POLICY "Users can delete own excel files"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'uploaded-excels' AND auth.uid() = owner);
